{
 "title": "New dashboar d",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vendas por Categoria",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "vendasdb",
     "rawSql": "SELECT c.name AS categoria, SUM(s.value) AS total\r\nFROM sales s\r\nJOIN categories c ON c.id = s.category_id\r\nGROUP BY c.name\r\nORDER BY total DESC;\r\n"
    }
   ]
  },
  {
   "title": "Ultimas Vendas",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "vendasdb",
     "rawSql": "SELECT\r\n  s.id,\r\n  c.name AS categoria,\r\n  s.value,\r\n  s.created_at\r\nFROM sales s\r\nJOIN categories c ON c.id = s.category_id\r\nORDER BY s.created_at DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Total de Vendas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vendasdb",
     "rawSql": "SELECT SUM(value) AS total_vendas\r\nFROM sales;\r\n"
    }
   ]
  },
  {
   "title": "Ticket médio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "vendasdb",
     "rawSql": "SELECT AVG(value) AS media_vendas\r\nFROM sales;"
    }
   ]
  },
  {
   "title": "Request por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request por por rota",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentual de erros",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status_code=~\"5..\"}[5m]))\r\n      /\r\n    sum(rate(http_requests_total[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta por rota",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (route)\r\n/\r\nsum(rate(http_request_duration_seconds_count[5m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "increase(http_requests_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histograma de latência",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}